name: Testing Hello Youhana Action

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -  uses: actions/setup-node@v1
       with:
         node-version: 12.4
    - uses: actions/checkout@v2
    - uses: youhananaseim/hello-youhana-action@master
